version: '3.2'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: ghsync
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "8081:15672"
      - "5672:5672"

volumes:
  postgres:
    external: false
